.circleci/config.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Enable preprod and prod deployments
Correct ingress URL / host

ESWE-810 Front End 

---

helm_deploy/hmpps-jobs-board-ui/values.yaml
package-lock.json

Add missing environment variable - PASSPHRASE
**Reviewers**
@gary-dutton-moj

Env variables

---

.gitignore
cypress.config.ts
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.ts
server/utils/nunjucksSetup.ts
server/views/pages/employers/employerList/index.njk
server/views/pages/jobs/jobList/index.njk

- Added new url env config for Work after release link
- Updated work after release links
- Updated cypress config to allow longer tests
- Updated gitignore to ignore private tests

ESWE-1043_work_after_release_link Added url for work after release

---

server/routes/jobs/jobList/jobListController.ts
server/views/pages/employers/employerList/index.njk

- Fixed default sort redirect
- Fixed tab link

jobs_sort_redirect_fix Fixed default sort redirect, and tab link

---

.circleci/config.yml

[ESWE-1059] Deploy to preprod

---

server/app.ts
server/views/partials/dpsFooter.njk
server/views/partials/dpsHeader.njk

Get components on POST as well as GET so the header is loaded on failed validation

Fix get components on post

---

integration_tests/mockApis/auth.ts
server/middleware/authorisationMiddleware.ts

Allow NFN users to run the service.

ESWE-1083 - allow access to external NFN users

---

server/routes/jobs/jobHowToApplyUpdate/jobHowToApplyUpdateController.ts
server/views/pages/jobs/jobReview/partials/_howToApplySection.njk

- Fixed bug where closing date cant be cleared when you change to a Rolling job

ESWE-1089_clear_closing_date_bug

---

server/constants/contentLookup/workPattern.ts
server/routes/jobs/jobContractUpdate/validationSchema.test.ts
server/routes/jobs/jobContractUpdate/validationSchema.ts

Fixed contract type content, post code content

ESWE-1095_add_job_bugs

---

server/middleware/authorisationMiddleware.ts

**DEBUGGING ONLY**
Add additional logger info to inspect roles used in authenticationMiddleware.

Debug and fix user access error

---

server/constants/contentLookup/employerStatus.ts
server/views/pages/employers/employerUpdate/index.njk

Updated content for employer status

ESWE-1102_employer_status_content_update

---

helm_deploy/hmpps-jobs-board-ui/values.yaml
server/config.ts
server/utils/nunjucksSetup.ts
server/views/partials/layout.njk

Configure Google Tag Manager (GTM) for tracking.

ESWE-1103: setup and configure google tag manager

---

server/routes/jobs/jobReview/jobReviewController.ts

- Added temporary logging
- Added defensive coding around handling id parameter

Fix_production_guid_error Added defensive coding and additional logging

---

server/routes/employers/employerReview/employerReviewController.ts
server/routes/jobs/jobReview/jobReviewController.ts

Fix production guid error

---

server/routes/employers/employerUpdate/validationSchema.test.ts
server/routes/employers/employerUpdate/validationSchema.ts

Updated max length of employerDescription

ESWE-1104_change_request_employer_description_length 

---

package-lock.json
package.json
server/app.ts
server/config.ts
server/index.ts
server/testutils/appSetup.ts
server/utils/azureAppInsights.test.ts
server/utils/azureAppInsights.ts
server/utils/nunjucksSetup.ts
server/views/partials/layout.njk

- Enable [Azure Monitor AppInsights real user monitoring](https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-sdk?tabs=npmpackage)
- Implement [DPS - tracking users in log analytics](https://dsdmoj.atlassian.net/wiki/spaces/NDSS/pages/5254381673/Tracking+users+in+Log+Analytics)

set up metrics tracking - appinsights config

---

.circleci/config.yml
package-lock.json
package.json
server/app.ts
server/middleware/sanitizeBody.test.ts
server/middleware/sanitizeBody.ts
server/middleware/sanitizeQuery.test.ts
server/middleware/sanitizeQuery.ts
server/middleware/setUpWebSecurity.ts
server/views/partials/layout.njk

Eswe 1173 sanitize user input

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Adjust severity alerts after setting up alert manager. Alert severity are:
- dev / preprod: `education-alerts-non-prod`
- prod: `education-alerts`

update prometheus alerts

---

server/routes/jobs/jobRoleUpdate/validationSchema.test.ts
server/routes/jobs/jobRoleUpdate/validationSchema.ts

- Added new validation rule for numberOfVacancies

ESWE-1216_handle_negative_values

---

integration_tests/e2e/createJob.cy.ts
integration_tests/e2e/updateJob.cy.ts
server/routes/jobs/jobContractUpdate/validationSchema.test.ts
server/routes/jobs/jobContractUpdate/validationSchema.ts

- Updated regex to require spaces in postcode
- Updated relevant tests

ESWE-1231_update_validation_rule_postcode_no_spaces

---

server/views/pages/employers/employerUpdate/index.njk
server/views/pages/jobs/jobContractUpdate/index.njk
server/views/pages/jobs/jobHowToApplyUpdate/index.njk
server/views/pages/jobs/jobRequirementsUpdate/index.njk
server/views/pages/jobs/jobReview/partials/_contractSection.njk
server/views/pages/jobs/jobReview/partials/_requirementsSection.njk
server/views/pages/jobs/jobReview/partials/_roleSection.njk
server/views/pages/jobs/jobRoleUpdate/index.njk

- Decode values when populating fields to prevent double encoding

ESWE-1257_fix_double_encoding_special_characters

---

.eslintrc.json
server/utils/columnSort.test.ts
server/views/pages/employers/employerList/partials/_employerListFilters.njk
server/views/pages/employers/employerList/partials/_notFoundMessages.njk
server/views/pages/jobs/jobList/partials/_jobListFilters.njk
server/views/pages/jobs/jobList/partials/_notFoundMessages.njk
tsconfig.json

- TS config to match other projects
- safe on filters

FIX_ts_errors_and_safe_filters Fixed 

---

package-lock.json
package.json

Dependencies update, including...
- [trivy scan](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-jobs-board-ui/534/workflows/68cd4118-6936-41d7-ae5c-e1c0ea33991c/jobs/2259)
- [security audit](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-jobs-board-ui/534/workflows/68cd4118-6936-41d7-ae5c-e1c0ea33991c/jobs/2258)
- govuk-frontend

update various libraries dependencies
